Load_LS()
{
	// CreateFuelOutlet(1941.65625, -1778.45313, 14.14063, 2.0, 100.0, frandom(40.0));
	// CreateFuelOutlet(1941.65625, -1774.31250, 14.14063, 2.0, 100.0, frandom(40.0));
	// CreateFuelOutlet(1941.65625, -1771.34375, 14.14063, 2.0, 100.0, frandom(40.0));
	// CreateFuelOutlet(1941.65625, -1767.28906, 14.14063, 2.0, 100.0, frandom(40.0));

	// CreateZipline(
	// 	2159.08, -986.47, 70.59,
	// 	2063.30, -993.57, 59.38);

	// CreateZipline(
	// 	2152.75, -1027.94, 73.47,
	// 	2191.36, -1051.42, 57.25);

	// CreateZipline(
	// 	2228.26, -1120.77, 48.88,
	// 	2200.78, -1096.47, 42.13);

	LS_District_Housing1();
	LS_District_Housing2();
	LS_District_Housing3();
	LS_District_Housing4();
	LS_District_EastBeach();
	LS_District_Industrial();
	LS_District_Docks();
	LS_District_Airport();
	LS_District_SantaMaria();
	LS_District_City1();
	LS_District_City2();
	LS_District_City3();

	// DefineSupplyDropPos("Los Santos Docks", 2760.28491, -2443.92456, 12.47645);
	// DefineSupplyDropPos("Los Santos Airport", 2092.42188, -2219.47021, 12.50092);
	// DefineSupplyDropPos("Los Santos Verdant Bluffs", 1134.69092, -2037.15295, 67.97311);
	// DefineSupplyDropPos("Los Santos Pier", 370.06274, -2025.17505, 6.64495);
	// DefineSupplyDropPos("Los Santos Market Station", 801.16882, -1322.54480, 12.35861);
	// DefineSupplyDropPos("Los Santos North Car Park", 1711.01563, -1053.82056, 22.97256);
	// DefineSupplyDropPos("Los Santos Jefferson Motel", 2217.05444, -1163.08008, 24.70885);
}


LS_District_Housing1()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Housing1' please wait...");
}

LS_District_Housing2()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Housing2' please wait...");

	CreateItem(item_Workbench, 2458.86377, -1974.19800, 12.45251, 0.0, 0.0, -91.14005);
}

LS_District_Housing3()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Housing3' please wait...");
}

LS_District_Housing4()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Housing4' please wait...");
}

LS_District_EastBeach()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_EastBeach' please wait...");
}

LS_District_Industrial()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Industrial' please wait...");
}

LS_District_Docks()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Docks' please wait...");
}

LS_District_Airport()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_Airport' please wait...");
}

LS_District_SantaMaria()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_SantaMaria' please wait...");
}

LS_District_City1()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_City1' please wait...");
}

LS_District_City2()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_City2' please wait...");
}

LS_District_City3()
{
	// ChatMsgAll(YELLOW, " >  Loading world region: 'LS_District_City3' please wait...");
}
